import {
  LeetGlyphA,
  LeetGlyphB,
  LeetGlyphC,
  LeetGlyphD,
  LeetGlyphE,
  LeetGlyphF,
  LeetGlyphG,
  LeetGlyphH,
  LeetGlyphI,
  LeetGlyphJ,
  LeetGlyphK,
  LeetGlyphL,
  LeetGlyphM,
  LeetGlyphN,
  LeetGlyphO,
  LeetGlyphP,
  LeetGlyphQ,
  LeetGlyphR,
  LeetGlyphS,
  LeetGlyphT,
  LeetGlyphU,
  LeetGlyphV,
  LeetGlyphW,
  LeetGlyphX,
  LeetGlyphY,
  LeetGlyphZ,
} from "../../enums/LeetGlyph";

const LeetGlyphs = {
  a: Object.values(LeetGlyphA),
  b: Object.values(LeetGlyphB),
  c: Object.values(LeetGlyphC),
  d: Object.values(LeetGlyphD),
  e: Object.values(LeetGlyphE),
  f: Object.values(LeetGlyphF),
  g: Object.values(LeetGlyphG),
  h: Object.values(LeetGlyphH),
  i: Object.values(LeetGlyphI),
  j: Object.values(LeetGlyphJ),
  k: Object.values(LeetGlyphK),
  l: Object.values(LeetGlyphL),
  m: Object.values(LeetGlyphM),
  n: Object.values(LeetGlyphN),
  o: Object.values(LeetGlyphO),
  p: Object.values(LeetGlyphP),
  q: Object.values(LeetGlyphQ),
  r: Object.values(LeetGlyphR),
  s: Object.values(LeetGlyphS),
  t: Object.values(LeetGlyphT),
  u: Object.values(LeetGlyphU),
  v: Object.values(LeetGlyphV),
  w: Object.values(LeetGlyphW),
  x: Object.values(LeetGlyphX),
  y: Object.values(LeetGlyphY),
  z: Object.values(LeetGlyphZ),
};

export default LeetGlyphs;
