import {
  UnicodeGlyphA,
  UnicodeGlyphB,
  UnicodeGlyphC,
  UnicodeGlyphD,
  UnicodeGlyphE,
  UnicodeGlyphF,
  UnicodeGlyphG,
  UnicodeGlyphH,
  UnicodeGlyphI,
  UnicodeGlyphJ,
  UnicodeGlyphK,
  UnicodeGlyphL,
  UnicodeGlyphM,
  UnicodeGlyphN,
  UnicodeGlyphO,
  UnicodeGlyphP,
  UnicodeGlyphQ,
  UnicodeGlyphR,
  UnicodeGlyphS,
  UnicodeGlyphT,
  UnicodeGlyphU,
  UnicodeGlyphV,
  UnicodeGlyphW,
  UnicodeGlyphX,
  UnicodeGlyphY,
  UnicodeGlyphZ,
} from "../../enums/UnicodeGlyph";

const UnicodeGlyphs = {
  a: Object.values(UnicodeGlyphA),
  b: Object.values(UnicodeGlyphB),
  c: Object.values(UnicodeGlyphC),
  d: Object.values(UnicodeGlyphD),
  e: Object.values(UnicodeGlyphE),
  f: Object.values(UnicodeGlyphF),
  g: Object.values(UnicodeGlyphG),
  h: Object.values(UnicodeGlyphH),
  i: Object.values(UnicodeGlyphI),
  j: Object.values(UnicodeGlyphJ),
  k: Object.values(UnicodeGlyphK),
  l: Object.values(UnicodeGlyphL),
  m: Object.values(UnicodeGlyphM),
  n: Object.values(UnicodeGlyphN),
  o: Object.values(UnicodeGlyphO),
  p: Object.values(UnicodeGlyphP),
  q: Object.values(UnicodeGlyphQ),
  r: Object.values(UnicodeGlyphR),
  s: Object.values(UnicodeGlyphS),
  t: Object.values(UnicodeGlyphT),
  u: Object.values(UnicodeGlyphU),
  v: Object.values(UnicodeGlyphV),
  w: Object.values(UnicodeGlyphW),
  x: Object.values(UnicodeGlyphX),
  y: Object.values(UnicodeGlyphY),
  z: Object.values(UnicodeGlyphZ),
};

export default UnicodeGlyphs;
