export const DEFAULT_RANDOMIZABLE_ENABLED = false;
export const DEFAULT_RANDOMIZABLE_MAX_DELAY = 3000;
export const DEFAULT_RANDOMIZABLE_MIN_DELAY = 300;
export const DEFAULT_RANDOMIZABLE_SHOULD_REPEAT = true;

const DEFAULT_RANDOMIZABLE = {
  enabled: DEFAULT_RANDOMIZABLE_ENABLED,
  maxDelay: DEFAULT_RANDOMIZABLE_MAX_DELAY,
  minDelay: DEFAULT_RANDOMIZABLE_MIN_DELAY,
  shouldRepeat: DEFAULT_RANDOMIZABLE_SHOULD_REPEAT,
};

export default DEFAULT_RANDOMIZABLE;
