export const DEFAULT_RANDOM_STRING_PROPS_CENTER = false;
export const DEFAULT_RANDOM_STRING_PROPS_IGNORE_SPACES = true;
export const DEFAULT_RANDOM_STRING_PROPS_SIZE = 3;
export const DEFAULT_RANDOM_STRING_PROPS_TEXT = "random css";
